name: Google App Engine Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: grpc/php

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      
      - name: Check Python version
        run: python --version

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{SECRETS.GCLOUD_PROJECT_ID}}
          service_account_key: ${{SECRETS.GCLOUD_AUTH}}
          export_default_credentials: true

      - name: Deploy
        if: success()
        run: gcloud components install beta -q && gcloud beta app deploy -q --version=test --no-cache
